/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vueApp;

/**
 *
 * @author p1201072
 */
public class JDCreer extends javax.swing.JDialog {

    /**
     * Creates new form JDCreer
     */
    public JDCreer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPInfosGen = new javax.swing.JPanel();
        jLType = new javax.swing.JLabel();
        jCType = new javax.swing.JComboBox();
        jLCourt = new javax.swing.JLabel();
        jLDate = new javax.swing.JLabel();
        jLHeure = new javax.swing.JLabel();
        jCCourt = new javax.swing.JComboBox();
        jCDate = new javax.swing.JComboBox();
        jCHeure = new javax.swing.JComboBox();
        jPJoueur = new javax.swing.JPanel();
        jCEquipe1 = new javax.swing.JComboBox();
        jCEquipe2 = new javax.swing.JComboBox();
        jLEquipe1 = new javax.swing.JLabel();
        jLEquipe2 = new javax.swing.JLabel();
        jPPersonnel = new javax.swing.JPanel();
        jLArbitreChaise = new javax.swing.JLabel();
        jCArbitreChaise = new javax.swing.JComboBox();
        jLArbitreFilet = new javax.swing.JLabel();
        jCArbitreFilet = new javax.swing.JComboBox();
        jLArbitreLigne1 = new javax.swing.JLabel();
        jLArbitreLigne2 = new javax.swing.JLabel();
        jLArbitreLigne3 = new javax.swing.JLabel();
        jLArbitreLigne4 = new javax.swing.JLabel();
        jLArbitreLigne5 = new javax.swing.JLabel();
        jLArbitreLigne6 = new javax.swing.JLabel();
        jLArbitreLigne7 = new javax.swing.JLabel();
        jLArbitreLigne8 = new javax.swing.JLabel();
        jCArbitreLigne1 = new javax.swing.JComboBox();
        jCArbitreLigne2 = new javax.swing.JComboBox();
        jCArbitreLigne3 = new javax.swing.JComboBox();
        jCArbitreLigne4 = new javax.swing.JComboBox();
        jCArbitreLigne5 = new javax.swing.JComboBox();
        jCArbitreLigne6 = new javax.swing.JComboBox();
        jCArbitreLigne7 = new javax.swing.JComboBox();
        jCArbitreLigne8 = new javax.swing.JComboBox();
        jCRamasseur1 = new javax.swing.JComboBox();
        jCRamasseur2 = new javax.swing.JComboBox();
        jLRamasseur1 = new javax.swing.JLabel();
        jLRamasseur2 = new javax.swing.JLabel();
        jBValider = new javax.swing.JButton();
        jBAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPInfosGen.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations sur le match"));

        jLType.setText("Type de match");

        jCType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Double" }));
        jCType.setToolTipText("");
        jCType.setEditor(null);
        jCType.setName("Type"); // NOI18N
        jCType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTypeActionPerformed(evt);
            }
        });

        jLCourt.setText("Court");

        jLDate.setText("Date");

        jLHeure.setText("Heure");

        javax.swing.GroupLayout jPInfosGenLayout = new javax.swing.GroupLayout(jPInfosGen);
        jPInfosGen.setLayout(jPInfosGenLayout);
        jPInfosGenLayout.setHorizontalGroup(
            jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfosGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPInfosGenLayout.createSequentialGroup()
                        .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLType)
                            .addComponent(jLHeure)
                            .addComponent(jLDate))
                        .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPInfosGenLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInfosGenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCDate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPInfosGenLayout.createSequentialGroup()
                        .addComponent(jLCourt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPInfosGenLayout.setVerticalGroup(
            jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInfosGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLType)
                    .addComponent(jCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCCourt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDate)
                    .addComponent(jCDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPInfosGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLHeure)
                    .addComponent(jCHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPJoueur.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix des joueurs"));

        jLEquipe1.setText("Equipe 1");

        jLEquipe2.setText("Equipe 2");

        javax.swing.GroupLayout jPJoueurLayout = new javax.swing.GroupLayout(jPJoueur);
        jPJoueur.setLayout(jPJoueurLayout);
        jPJoueurLayout.setHorizontalGroup(
            jPJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPJoueurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEquipe1)
                    .addComponent(jLEquipe2))
                .addGap(57, 57, 57)
                .addGroup(jPJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCEquipe1, 0, 58, Short.MAX_VALUE)
                    .addComponent(jCEquipe2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPJoueurLayout.setVerticalGroup(
            jPJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPJoueurLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEquipe1))
                .addGap(27, 27, 27)
                .addGroup(jPJoueurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEquipe2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPPersonnel.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix du personnel"));

        jLArbitreChaise.setText("Arbitre de chaise");

        jLArbitreFilet.setText("Arbitre de filet");

        jLArbitreLigne1.setText("Arbitre de ligne 1");

        jLArbitreLigne2.setText("Arbitre de ligne 2");

        jLArbitreLigne3.setText("Arbitre de ligne 3");

        jLArbitreLigne4.setText("Arbitre de ligne 4");

        jLArbitreLigne5.setText("Arbitre de ligne 5");

        jLArbitreLigne6.setText("Arbitre de ligne 6");

        jLArbitreLigne7.setText("Arbitre de ligne 7");

        jLArbitreLigne8.setText("Arbitre de ligne 8");

        jCArbitreLigne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCArbitreLigne1ActionPerformed(evt);
            }
        });

        jCArbitreLigne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCArbitreLigne5ActionPerformed(evt);
            }
        });

        jLRamasseur1.setText("Equipe de ramasseurs de balles 1");

        jLRamasseur2.setText("Equipe de ramasseurs de balles 2");

        javax.swing.GroupLayout jPPersonnelLayout = new javax.swing.GroupLayout(jPPersonnel);
        jPPersonnel.setLayout(jPPersonnelLayout);
        jPPersonnelLayout.setHorizontalGroup(
            jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPersonnelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPersonnelLayout.createSequentialGroup()
                        .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPPersonnelLayout.createSequentialGroup()
                                .addComponent(jLRamasseur2)
                                .addGap(18, 18, 18)
                                .addComponent(jCRamasseur2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPPersonnelLayout.createSequentialGroup()
                                .addComponent(jLRamasseur1)
                                .addGap(18, 18, 18)
                                .addComponent(jCRamasseur1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPPersonnelLayout.createSequentialGroup()
                        .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPPersonnelLayout.createSequentialGroup()
                                .addComponent(jLArbitreLigne1)
                                .addGap(18, 18, 18)
                                .addComponent(jCArbitreLigne1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPPersonnelLayout.createSequentialGroup()
                                .addComponent(jLArbitreLigne3)
                                .addGap(18, 18, 18)
                                .addComponent(jCArbitreLigne3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPPersonnelLayout.createSequentialGroup()
                                .addComponent(jLArbitreChaise)
                                .addGap(18, 18, 18)
                                .addComponent(jCArbitreChaise, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPPersonnelLayout.createSequentialGroup()
                                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLArbitreLigne5)
                                    .addComponent(jLArbitreLigne7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCArbitreLigne7, 0, 45, Short.MAX_VALUE)
                                    .addComponent(jCArbitreLigne5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLArbitreFilet)
                            .addComponent(jLArbitreLigne2)
                            .addComponent(jLArbitreLigne4)
                            .addComponent(jLArbitreLigne6)
                            .addComponent(jLArbitreLigne8))
                        .addGap(18, 18, 18)
                        .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCArbitreFilet, 0, 45, Short.MAX_VALUE)
                            .addComponent(jCArbitreLigne2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCArbitreLigne4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCArbitreLigne6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCArbitreLigne8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        jPPersonnelLayout.setVerticalGroup(
            jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLArbitreChaise)
                    .addComponent(jLArbitreFilet)
                    .addComponent(jCArbitreFilet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCArbitreChaise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLArbitreLigne1)
                    .addComponent(jLArbitreLigne2)
                    .addComponent(jCArbitreLigne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCArbitreLigne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLArbitreLigne3)
                    .addComponent(jLArbitreLigne4)
                    .addComponent(jCArbitreLigne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCArbitreLigne4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLArbitreLigne5)
                    .addComponent(jLArbitreLigne6)
                    .addComponent(jCArbitreLigne5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCArbitreLigne6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLArbitreLigne8)
                        .addComponent(jCArbitreLigne8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCArbitreLigne7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLArbitreLigne7))
                .addGap(35, 35, 35)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCRamasseur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRamasseur1))
                .addGap(18, 18, 18)
                .addGroup(jPPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCRamasseur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRamasseur2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBValider.setText("Valider");

        jBAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPJoueur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPInfosGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPPersonnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBValider, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBAnnuler)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPInfosGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAnnuler)
                            .addComponent(jBValider))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTypeActionPerformed

    private void jCArbitreLigne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCArbitreLigne5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCArbitreLigne5ActionPerformed

    private void jCArbitreLigne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCArbitreLigne1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCArbitreLigne1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCreer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCreer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCreer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCreer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCreer dialog = new JDCreer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnnuler;
    private javax.swing.JButton jBValider;
    private javax.swing.JComboBox jCArbitreChaise;
    private javax.swing.JComboBox jCArbitreFilet;
    private javax.swing.JComboBox jCArbitreLigne1;
    private javax.swing.JComboBox jCArbitreLigne2;
    private javax.swing.JComboBox jCArbitreLigne3;
    private javax.swing.JComboBox jCArbitreLigne4;
    private javax.swing.JComboBox jCArbitreLigne5;
    private javax.swing.JComboBox jCArbitreLigne6;
    private javax.swing.JComboBox jCArbitreLigne7;
    private javax.swing.JComboBox jCArbitreLigne8;
    private javax.swing.JComboBox jCCourt;
    private javax.swing.JComboBox jCDate;
    private javax.swing.JComboBox jCEquipe1;
    private javax.swing.JComboBox jCEquipe2;
    private javax.swing.JComboBox jCHeure;
    private javax.swing.JComboBox jCRamasseur1;
    private javax.swing.JComboBox jCRamasseur2;
    private javax.swing.JComboBox jCType;
    private javax.swing.JLabel jLArbitreChaise;
    private javax.swing.JLabel jLArbitreFilet;
    private javax.swing.JLabel jLArbitreLigne1;
    private javax.swing.JLabel jLArbitreLigne2;
    private javax.swing.JLabel jLArbitreLigne3;
    private javax.swing.JLabel jLArbitreLigne4;
    private javax.swing.JLabel jLArbitreLigne5;
    private javax.swing.JLabel jLArbitreLigne6;
    private javax.swing.JLabel jLArbitreLigne7;
    private javax.swing.JLabel jLArbitreLigne8;
    private javax.swing.JLabel jLCourt;
    private javax.swing.JLabel jLDate;
    private javax.swing.JLabel jLEquipe1;
    private javax.swing.JLabel jLEquipe2;
    private javax.swing.JLabel jLHeure;
    private javax.swing.JLabel jLRamasseur1;
    private javax.swing.JLabel jLRamasseur2;
    private javax.swing.JLabel jLType;
    private javax.swing.JPanel jPInfosGen;
    private javax.swing.JPanel jPJoueur;
    private javax.swing.JPanel jPPersonnel;
    // End of variables declaration//GEN-END:variables
}
